function row = metricsRow(name, m)
    row = table({name}, m.finalValue, m.steadyStateError, m.overshootPercent, ...
        m.riseTime, m.settlingTime2Percent, m.IAE, m.ITAE, ...
        'VariableNames', {'controller', 'final_value', 'steady_state_error', ...
        'overshoot_percent', 'rise_time_s', 'settling_time_2pct_s', 'IAE', 'ITAE'});
end
